In [1]:
import numpy as np

In [2]:
arr=np.array([[1,5,4,6,7,5],[1,5,4,6,7,5]])
arr1=np.array([1,5,4,6,7,5])

In [3]:
arr.shape

(2, 6)

In [4]:
arr.dtype

dtype('int32')

In [5]:
arr.ndim

2

In [6]:
arr.size

12

In [7]:
arr.itemsize

4

In [8]:
arr[3:]

array([], shape=(0, 6), dtype=int32)

In [9]:
arr[:]

array([[1, 5, 4, 6, 7, 5],
       [1, 5, 4, 6, 7, 5]])

In [28]:
# Slicing of n-dimentional arrays
arr[0,:]

array([1, 5, 4, 6, 7, 5])

In [10]:
arr1[2:]

array([4, 6, 7, 5])

In [11]:
print(arr1*np.array([2,2,2,2,2,2]))

[ 2 10  8 12 14 10]


In [12]:
print(arr1*2)

[ 2 10  8 12 14 10]


In [13]:
# working with list and arrays
list1=[3,4,5,6]
array1=np.array([3,4,5,6])


In [14]:
print("List Elements:",list1*2)
print("Array Elements:",array1*2)

List Elements: [3, 4, 5, 6, 3, 4, 5, 6]
Array Elements: [ 6  8 10 12]


In [15]:
print("List:",list1+[2])
print("Array:",array1+[2])

List: [3, 4, 5, 6, 2]
Array: [5 6 7 8]


In [16]:
print(np.sqrt(array1))
print(np.mod(array1,5))
print(np.log(array1))

[1.73205081 2.         2.23606798 2.44948974]
[3 4 0 1]
[1.09861229 1.38629436 1.60943791 1.79175947]


In [17]:
print(np.sqrt(list1))
print(np.mod(list1,5))
print(np.log(list1))

[1.73205081 2.         2.23606798 2.44948974]
[3 4 0 1]
[1.09861229 1.38629436 1.60943791 1.79175947]


In [18]:
list2=[5,6,3,8]
array2=np.array(list2)
print("The dot product of-")

print("Array is:",np.dot(array1,array2))



The dot product of-
Array is: 102


In [19]:
# Modern syntax to find the dot product
sum = array1 @ array2
print(sum)

102


In [20]:
# Working with mathematical function defined in numpy
# Printing the Traverse of the array matrix
print(arr.T)

[[1 1]
 [5 5]
 [4 4]
 [6 6]
 [7 7]
 [5 5]]


In [21]:
m_array=np.array([[2,3,6],[5,8,6],[2,9,5]])

In [22]:
print(m_array,"\nThe dimension is",m_array.ndim,"\nThe shape is",m_array.shape,"\nThe size is",m_array.size,"\nThe itemsize is",m_array.itemsize)

[[2 3 6]
 [5 8 6]
 [2 9 5]] 
The dimension is 2 
The shape is (3, 3) 
The size is 9 
The itemsize is 4


In [23]:
# the transpose of the array matrix is
print(m_array.T)

[[2 5 2]
 [3 8 9]
 [6 6 5]]


In [35]:
bool_arr=arr>2
print(bool_arr)
print(arr[bool_arr])
print(arr[arr>2])

[[False  True  True  True  True  True]
 [False  True  True  True  True  True]]
[5 4 6 7 5 5 4 6 7 5]
[5 4 6 7 5 5 4 6 7 5]


In [46]:
np.where(arr>2,arr,-1)

array([[-1,  5,  4,  6,  7,  5],
       [-1,  5,  4,  6,  7,  5]])

In [63]:
arr3=np.array([34,65,14,86,31,17,56])
list3=[1,3,5]
print(arr3[list3])

[65 86 17]


In [58]:
even=np.argwhere(arr3%2==0).flatten()
print(even)
print(arr3[even])

[0 2 3 6]
[34 14 86 56]


In [70]:
# Reshaping the dimention of array matrix
b=np.arange(1,7)
b.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])